#!/bin/bash

echo "Update"
sudo apt update

echo "Installation..."
echo "Changement de la source"
echo deb http://ftp.free.fr/pub/kali kali-rolling main contrib non-free non-free-firmware | sudo tee /etc/apt/sources.list

sudo apt install seclists bloodhound wafw00f ruby python-pip python3 python3-pip python3-argcomplete xclip netexec
sudo apt install go





#LAZAGNE
wget https://github.com/AlessandroZ/LaZagne/releases/download/v2.4.5/LaZagne.exe
wget https://raw.githubusercontent.com/AlessandroZ/LaZagne/master/Linux/laZagne.py

git clone https://github.com/AlessandroZ/LaZagne.git
cd lazagne
pip install -r requirements.txt
cd ..

#identywaf
wget https://raw.githubusercontent.com/stamparm/identYwaf/master/identYwaf.py

#webshell php cool
wget https://raw.githubusercontent.com/Arrexel/phpbash/master/phpbash.min.php
wget https://raw.githubusercontent.com/Arrexel/phpbash/master/phpbash.php


#CREATE
## Usernames
wget https://raw.githubusercontent.com/urbanadventurer/username-anarchy/master/username-anarchy

git clone https://github.com/urbanadventurer/username-anarchy.git

## Wordlists
git clone https://github.com/Mebus/cupp.git

wget https://raw.githubusercontent.com/digininja/RSMangler/master/rsmangler.rb

git clone https://github.com/sc0tfree/mentalist.git

##OTher
sudo pip3 install defaultcreds-cheat-sheet
#creds search tomcat



#CMS
#git clone https://github.com/SamJoan/droopescan.git
sudo pip install droopescan


## WORDPRESS
sudo gem install terminal-table
git clone https://github.com/delvelabs/vane.git

## JOOMLA
wget https://raw.githubusercontent.com/ajnik/joomla-bruteforce/master/joomla-brute.py

git clone https://github.com/rezasp/joomscan.git
#cd joomscan
#perl joomscan.pl

git clone https://github.com/drego85/JoomlaScan.git

##TOMCAT
wget https://raw.githubusercontent.com/tennc/webshell/master/fuzzdb-webshell/jsp/cmd.jsp
wget https://raw.githubusercontent.com/b33lz3bub-1/Tomcat-Manager-Bruteforce/master/mgr_brute.py



## Splunk
git clone https://github.com/0xjpuff/reverse_shell_splunk.git

## XSS
git clone https://github.com/s0md3v/XSStrike.git
git clone https://github.com/epsylon/xsser.git
git clone https://github.com/rajeshmajumdar/BruteXSS.git


#Obfuscator
git clone https://github.com/Bashfuscator/Bashfuscator
cd Bashfuscator
sudo python3 setup.py install --user
cd ..

git clone https://github.com/danielbohannon/Invoke-DOSfuscation.git


## LFI
git clone http://github.com/mzfr/liffy
cd liffy
sudo pip3 install -r requirements.txt
cd ..

git clone https://github.com/OsandaMalith/LFiFreak.git

echo "CHECK LFISUITE"
git clone https://github.com/D35m0nd142/LFISuite.git


## AD
git clone https://github.com/CiscoCXSecurity/linikatz.git
git clone https://github.com/bats3c/darkarmour.git
git clone https://github.com/FSecureLABS/SharpGPOAbuse.git
git clone https://github.com/Ridter/noPac.git
git clone https://github.com/SnaffCon/Snaffler.git
mkdir PrintNightmare && cd PrintNightmare &&wget https://raw.githubusercontent.com/cube0x0/CVE-2021-1675/main/CVE-2021-1675.py
cd ..
git clone https://github.com/topotam/PetitPotam.git


###impacket exe
git clone https://github.com/maaaaz/impacket-examples-windows.git

##LINUX
git clone https://github.com/huntergregal/mimipenguin.git

git clone https://github.com/galkan/crowbar.git


#SSL
sudo pip3 install shcheck

git clone --depth 1 https://github.com/drwetter/testssl.sh.git


#HTTP
go install -v github.com/projectdiscovery/interactsh/cmd/interactsh-client@latest
git clone https://github.com/FSecureLABS/GWTMap.git
git clone https://github.com/Dheerajmadhukar/4-ZERO-3.git
git clone https://github.com/devploit/dontgo403.git

#ALL
git clone https://github.com/swisskyrepo/PayloadsAllTheThings.git

#DNS
git clone https://github.com/Kinjutsu00/DnsExfiltration.git
git clone https://github.com/Arno0x/DNSExfiltrator.git
git clone https://github.com/TheRook/subbrute.git

#TUNNELING
git clone https://github.com/nccgroup/SocksOverRDP.git
git clone https://github.com/utoni/ptunnel-ng.git
go install github.com/jpillora/chisel@latest
git clone https://github.com/klsecservices/rpivot.git
cd rpivot && wget https://github.com/klsecservices/rpivot/releases/download/v1.0/client.exe
cd ..
git clone https://github.com/iagox86/dnscat2.git

wget https://github.com/nicocha30/ligolo-ng/archive/refs/tags/v0.4.4.zip
unp v0.4.4.zip
cd ligolo-ng-0.4.4
go build -o agent cmd/agent/main.go
go build -o proxy cmd/proxy/main.go
echo" [LIGOLO] your username :"
read username_ligolo
sudo ip tuntap add user username_ligolo mode tun ligolo
sudo ip link set ligolo up

#PRIVESC
git clone https://github.com/lefayjey/linWinPwn
cd linWinPwn; chmod +x linWinPwn.sh

apt install pipx git
pipx ensurepath
sudo pipx install git+https://github.com/Pennyw0rth/NetExec

git clone https://github.com/rebootuser/LinEnum.git
apt install python3-pip && sudo apt-get install libpcap-dev && sudo pip3 install Cython && sudo pip3 install python-libpcap

git clone https://github.com/DanMcInerney/net-creds.git
git clone https://github.com/whotwagner/logrotten.git
git clone https://github.com/DominicBreuker/pspy.git
git clone https://github.com/The-Z-Labs/linux-exploit-suggester.git
git clone https://github.com/arthepsy/CVE-2021-4034.git
git clone https://github.com/blasty/CVE-2021-3156.git
git clone https://github.com/dirtycow/dirtycow.github.io.git

PRIVESC
|-net-creds                     sniff data from int or pcap
|-CVE-2021-4034                 pkexec poc
|-CVE-2021-3156                 sudo abuse
|-dirty-cow                     dirtycow
LIN
|-Linux-exploit-suggester       Linux exploit sugg
|-LinEnum                       Local linux enum & privesc
|-pspy                          spy ps
WIN
|-PCredz                        Extract info such as Credt,NTLM,...
|-LogRotten                     Log rotate vuln


ALL
|
|-PayloadAllTheThings           Bible bru

AD
|
|-Linikatz
|-Darkarmour                    evade?
|-SharpGPOAbuse                 GPO_abuse
|-Impacket-examples-windows     impacket_exe
|-Snaffler                      find candy creds, ..
|-NetExec                       New CrackMapExec
|-linWinPwn                     Automate AD scanner
|-NoPac                         Special vuln
|-PrintNightmare                Special vuln
|-PetitPotam                    Special vuln

LINUX
|
|-mimipenguin                   show credentials (admin)
|-Crowbar                       bruteforce SSH Key
|-linux-exploit-suggester       LINUX suggester

SSL
|
|-shcheck                       check security attributes
|-testssl                       test SSL vulnerabilities

HTTP
|
|-interactsh                    OOB interaction gathering
|-GWTMap                        GoogleWebToolkit Map
|-4-ZERO-3                      403 bypass SH
|-Dontgo403                     403 bypass go

DNS
|
|-DnsExfiltration               Dns Exfiltrator
|-DnsExfiltrator                Same but different
|-subbrute                      enum DNS records & subs

VNP
|
|-SocksOverRDP                  Socks4/5 over RDP/CITRIX/..
|-ptunnel-ng                    TCP through ICMP
|-chisel                        TCP/UDP tunnel over HTTP
|-dnscat2                       DNS tunnel
|-Ligolo-ng                     La base 
